# Generated by Django 2.2.8 on 2020-08-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='navers',
            field=models.ManyToManyField(related_name='projects', to='navers.Naver'),
        ),
    ]
