# Generated by Django 2.2.8 on 2020-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birthdate', models.DateField(verbose_name='Data de nascimento')),
                ('admission_date', models.DateField(verbose_name='Data de admissão')),
                ('job_role', models.IntegerField(choices=[(1, 'Desenvolvedor'), (2, 'Engenheiro de software'), (3, 'DBA'), (4, 'Gerente de projetos'), (5, 'DevOps')], default=1, verbose_name='Cargo')),
            ],
        ),
    ]
